version: "2"
networks:
  ficus-tracker-backend-proxy:
    driver: "bridge"

services:
  postgres:
    container_name: "postgres"
    build: "postgres"
    networks:
      - "ficus-tracker-backend-proxy"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    build: "nginx"
    container_name: "nginx"
    ports:
      - 80:80
    networks:
      - "ficus-tracker-backend-proxy"


