version: "2"
#networks:
#  ficus-tracker-backend-proxy:
#    driver: "bridge"

services:
  postgres:
    container_name: "postgres"
    build: "postgres"
    networks:
      - "host"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    build: "nginx"
    container_name: "nginx"
    ports:
      - 80:80
    networks:
      - "host"
  ficus-tracker:
    build: "ficus-tracker"
    container_name: "ficus-tracker"
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - "host"



