version: "2"
#networks:
#  ficus-tracker-backend-proxy:
#    driver: "bridge"

services:
  postgres:
    container_name: "postgres"
    build:
      context: postgres
      network: host
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    build:
      context: nginx
      network: host
    container_name: "nginx"
    ports:
      - 80:80
  ficus-tracker:
    build:
      context: ficus-tracker
      network: host
    container_name: "ficus-tracker"
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: "${DATABASE_URL}"



